# Generated by Django 4.0.6 on 2022-07-26 20:39

from django.db import migrations
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp',
            field=localflavor.mx.models.MXCURPField(blank=True, max_length=18),
        ),
    ]
