# Generated by Django 4.0.6 on 2022-07-26 20:53

from django.db import migrations
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cp',
            field=localflavor.mx.models.MXRFCField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='rfc',
            field=localflavor.mx.models.MXRFCField(blank=True, max_length=13),
        ),
    ]
