# Generated by Django 4.0.6 on 2022-07-26 20:54

from django.db import migrations
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cp_user_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=localflavor.mx.models.MXZipCodeField(blank=True, max_length=5),
        ),
    ]
