# Generated by Django 4.0.6 on 2022-07-27 07:11

import applications.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(max_length=13, validators=[applications.users.validators.rfc_validation]),
        ),
    ]
