# Generated by Django 4.0.6 on 2022-07-27 08:01

import applications.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=models.CharField(blank=True, max_length=5, validators=[applications.users.validators.cp_validation]),
        ),
    ]
