# Generated by Django 4.0.6 on 2022-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_date_of_birth_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('1', 'Administrador'), ('2', 'Lectura'), ('3', 'Lectura/Escritura')], max_length=1),
        ),
    ]
