# Generated by Django 4.0.6 on 2022-07-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('1', 'Administrador'), ('2', 'Lectura'), ('3', 'Lectura/Escritura')], default='2', max_length=1),
        ),
    ]
